### ISSUE TITLE
Lunix support 

### ISSUE THREAD

**Issue by luthermarcus** [emarkproject/eMark#15]
I would like to build wallet on ubuntu. Seems like there is no directions and normal building wont work.

**Comment by xBlackEye** [comment]
`sudo apt-get install qt4-dev-tools libboost-dev libboost-thread-dev libboost-program-options-dev libboost-filesystem-dev libboost-system-dev libdb++-dev libminiupnpc-dev libssl-dev`
`git clone https://github.com/emarkproject/eMark`
`cd eMark`
`qmake`
`make`

Start the bc wallet with:
`cd eMark`
`./eMark-qt`

Does it work? :)
