### ISSUE TITLE
Build fails with PIE enabled

### ISSUE THREAD

**Issue by mibe** [emarkproject/eMark#19]
I tried to compile the wallet today, with PIE enabled. That failed when building libmemenv.a from leveldb:

> relocation R_X86_64_32S against `_ZTVN7leveldb2DBE' can not be used when making a shared object; recompile with -fPIC

I worked around that issue with hacking the `-fPIC` into `build_config.mk` and commenting out the platform detection in leveldb's Makefile.

[There's a bug filed at Gentoo's bugtracker about this problem](https://bugs.gentoo.org/show_bug.cgi?id=505320), which has a patch attached. I didn't test this patch, since I hacked the `-fPIC` earlier. But maybe you could have a look at it?

I compiled the walled on a fresh box with Debian 8.5 amd64 installed.

**Comment by Broatcast** [comment]
fixed it here https://github.com/emarkproject/eMark/commit/9588f679aff66b64d3c7a7a208f2461c1e4407bf
