### ISSUE TITLE
make end with error

### ISSUE THREAD

**Issue by AndreyNag** [emarkproject/eMark#23]
When i`m execut make in src/ an error appear.
`g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOS
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_S
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crti.o: нераспознанное перемещение (0x2a) в
/usr/bin/ld: final link failed: Некорректное значение
collect2: error: ld returned 1 exit status
make: *** [eMarkd] Ошибка 1
`

When i`m execute qmake eMark-qt.pro then make an other error appear:
`/usr/bin/ld: cannot find -lboost_system-mgw49-mt-s-1_57
/usr/bin/ld: cannot find -lboost_filesystem-mgw49-mt-s-1_57
/usr/bin/ld: cannot find -lboost_program_options-mgw49-mt-s-1_57
/usr/bin/ld: cannot find -lboost_thread-mgw49-mt-s-1_57
collect2: error: ld returned 1 exit status
make: *** [eMark-qt] Ошибка 1

I`ve try sudo apt-get install git nano build-essential libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev

download source from https://github.com/emarkproject/eMark/releases/tag/1.4 and then:
`
cd eMark/src
make -f makefile.unix
But an error appear again:
`~/eMark-1.4/src$ make -f makefile.unix
/bin/sh ../share/genbuild.sh obj/build.h
fatal: Not a git repository (or any of the parent directories): .git
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/root2pool/eMark-1.4/src -I/home/root2pool/eMark-1.4/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/root2pool/eMark-1.4/src/leveldb/include -I/home/root2pool/eMark-1.4/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o eMarkd obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/timedata.o obj/script.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/bloom.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/root2pool/eMark-1.4/src/leveldb/libleveldb.a /home/root2pool/eMark-1.4/src/leveldb/libmemenv.a
obj/util.o: In function `boost::program_options::detail::basic_config_file_iterator<char>::getline(std::string&)':
/usr/include/boost/program_options/detail/config_file.hpp:161: undefined reference to `boost::program_options::to_internal(std::string const&)'
obj/util.o: In function `boost::program_options::detail::basic_config_file_iterator<char>::basic_config_file_iterator(std::istream&, std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)':
/usr/include/boost/program_options/detail/config_file.hpp:145: undefined reference to `boost::program_options::detail::common_config_file_iterator::common_config_file_iterator(std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)'
collect2: error: ld returned 1 exit status
make: *** [eMarkd] Ошибка 1
`
In my system loaded libboost-1.58 etc.
Ubuntu server 16.04LTS with actually updates.
Please help me.
Thanks you.

**Comment by xBlackEye** [comment]
https://forum.deutsche-emark.de/showthread.php?tid=457
Here is a guide for emark-qt & emarkd for Linux

**Comment by AndreyNag** [comment]
I have read this manual. Same error.
Perhaps the reason for the conflict versions of the operating system and/or system libraries? What libraries to pay attention to?

**Comment by Rumhocker** [comment]
i think eMark dont support boost 1.58 at this time. If you want, you can test copy the missing lines from here to the file chainparams.cpp
[](https://github.com/rat4/blackcoin/commit/843ca048cacafbcbf9225b2670a76d2887cf1b95)
Please give me a feedback if this work, then i can add this to eMark.

**Comment by Rumhocker** [comment]
https://github.com/rat4/blackcoin/commit/843ca048cacafbcbf9225b2670a76d2887cf1b95

**Comment by Rumhocker** [comment]
today i have testing build eMark-qt with updated boost 1.58 - with no problems.
