### ISSUE TITLE
timestamp too far in the future ERROR: ProcessBlock() : CheckBlock FAILED

### ISSUE THREAD

**Issue by Jack555555** [emarkproject/eMark#30]
ERROR: CheckBlock() : block timestamp too far in the future
ERROR: ProcessBlock() : CheckBlock FAILED

**Comment by Rumhocker** [comment]
It is a bug on time settings (time-stamp issue) on your machine.

**Comment by Broatcast** [comment]
I think this can be closed since there is no respond from the issue opener, this is a false configuration at os basis, not a problem with the wallet.
