### ISSUE TITLE
Why the F doesn't this comipile?

### ISSUE THREAD

**Issue by dem-ionz** [emarkproject/eMark#32]
Has anyone tried building this on ubuntu 17.04?

src/chainparams.cpp:96:52: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘boost::assign_detail::generic_list<int>’)
         base58Prefixes[SCRIPT_ADDRESS] = list_of(30);
                                                    ^

Many more of those other places.
 For example?

both headless, and QT fails.. And yes I checked the documentation. I would be a lot more behind this coin if the wallet was available, or even compiled, for Linux. There should be .deb packages for Ubuntu and Debian but there's not. Step your game up.

Makefile:1484: recipe for target 'build/chainparams.o' failed
make: *** [build/chainparams.o] Error 1

**Comment by Broatcast** [comment]
Building packages is not a good idea, to much negativ points for this.
I have no problems compiling it on Debian 7,8,9 ... i will test it on Ubuntu for you this days and see if i get any trubble.

**Comment by dem-ionz** [comment]
Ok, I will be interested in exactly what the process was if you got it working, if so, I will write up an install, for ubuntu 17.04 x 16.04 and update the documentation. :) 
Danke.

**Comment by Broatcast** [comment]
You are using 32 or 64 bit Ubuntu build?

**Comment by dem-ionz** [comment]
lost@keys:~$ uname -a -r
Linux keys 4.10.0-37-generic #41-Ubuntu SMP Fri Oct 6 20:20:37 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
lost@keys:~$ 

64 bit.

**Comment by Broatcast** [comment]
Ok, there are realy problems with building this on Ubuntu, i have wrote a fix but need to check if it still work on other systems with this, like debian and windows.

**Comment by dem-ionz** [comment]
Keep me posted, i'll do a write up, and post it to a repo of mine. you can clone it then. I can also do german to english translations if needed.

**Comment by Broatcast** [comment]
#33 You can test it with this patch, working for on Ubuntu 17.04 x64
include #34 and #35 if you like to fix all compiling warnings and errors.

**Comment by dem-ionz** [comment]
idk

ad -lrt -ldl -lQt5Widgets -lQt5Gui -lQt5Network -lQt5DBus -lQt5Core -lpthread -lGL 
build/miner.o: In function `void boost::this_thread::sleep_for<long, boost::ratio<1l, 1000l> >(boost::chrono::duration<long, boost::ratio<1l, 1000l> > const&)':
miner.cpp:(.text._ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE[_ZN5boost11this_thread9sleep_forIlNS_5ratioILl1ELl1000EEEEEvRKNS_6chrono8durationIT_T0_EE]+0x52): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
build/db.o: In function `CDB::Rewrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*)':
db.cpp:(.text+0x406f): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
build/walletdb.o: In function `ThreadFlushWalletDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
walletdb.cpp:(.text+0x43be): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
build/walletdb.o: In function `BackupWallet(CWallet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
walletdb.cpp:(.text+0x5ea5): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
walletdb.cpp:(.text+0x6032): undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
build/rpcclient.o: In function `CallRPC(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<json_spirit::Value_impl<json_spirit::Config_vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)':
rpcclient.cpp:(.text+0x1b61): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
build/rpcserver.o: In function `ServiceConnection(AcceptedConnection*)':
rpcserver.cpp:(.text+0xa744): undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
Makefile:514: recipe for target 'eMark-qt' failed
make: *** [eMark-qt] Error 1

**Comment by dem-ionz** [comment]
and headless. perhaps something on my end is messed up?

rpcwallet.cpp:624:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  std::string txcomment;
  ^~~
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/lost/patches/eMark/src -I/home/lost/patches/eMark/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/lost/patches/eMark/src/leveldb/include -I/home/lost/patches/eMark/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/wallet.d -o obj/wallet.o wallet.cpp
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/lost/patches/eMark/src -I/home/lost/patches/eMark/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/lost/patches/eMark/src/leveldb/include -I/home/lost/patches/eMark/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/walletdb.d -o obj/walletdb.o walletdb.cpp
g++ -c -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/lost/patches/eMark/src -I/home/lost/patches/eMark/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/lost/patches/eMark/src/leveldb/include -I/home/lost/patches/eMark/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/txdb-leveldb.d -o obj/txdb-leveldb.o txdb-leveldb.cpp
g++ -O2  -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/lost/patches/eMark/src -I/home/lost/patches/eMark/src/obj -DUSE_UPNP=0 -DENABLE_WALLET -I/home/lost/patches/eMark/src/leveldb/include -I/home/lost/patches/eMark/src/leveldb/helpers -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -o eMarkd obj/alert.o obj/version.o obj/checkpoints.o obj/netbase.o obj/addrman.o obj/crypter.o obj/key.o obj/init.o obj/bitcoind.o obj/keystore.o obj/core.o obj/main.o obj/net.o obj/protocol.o obj/rpcclient.o obj/rpcprotocol.o obj/rpcserver.o obj/rpcmisc.o obj/rpcnet.o obj/rpcblockchain.o obj/rpcrawtransaction.o obj/timedata.o obj/script.o obj/sync.o obj/txmempool.o obj/util.o obj/hash.o obj/bloom.o obj/noui.o obj/kernel.o obj/pbkdf2.o obj/chainparams.o obj/db.o obj/miner.o obj/rpcdump.o obj/rpcmining.o obj/rpcwallet.o obj/wallet.o obj/walletdb.o obj/txdb-leveldb.o -Wl,-z,relro -Wl,-z,now   -Wl,-Bdynamic -l boost_system -l boost_filesystem -l boost_program_options -l boost_thread -l db_cxx -l ssl -l crypto -l miniupnpc -Wl,-Bdynamic -l z -l dl -l pthread /home/lost/patches/eMark/src/leveldb/libleveldb.a /home/lost/patches/eMark/src/leveldb/libmemenv.a
obj/bitcoind.o: In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
obj/net.o: In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
obj/rpcclient.o: In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
obj/rpcserver.o: In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
obj/db.o: In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:235: undefined reference to `boost::this_thread::hiden::sleep_for(timespec const&)'
obj/walletdb.o:/usr/local/include/boost/thread/pthread/thread_data.hpp:235: more undefined references to `boost::this_thread::hiden::sleep_for(timespec const&)' follow
obj/walletdb.o: In function `boost::filesystem::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option)':
/usr/local/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
makefile.unix:178: recipe for target 'eMarkd' failed
make: *** [eMarkd] Error 1
root@keys:/home/lost/patches/eMark/src#

**Comment by Broatcast** [comment]
you missed some dependencies
try run: 
`sudo apt-get install build-essential libssl-dev libdb++-dev libboost-all-dev libminiupnpc-dev libqrencode-dev miniupnpc git`

**Comment by dem-ionz** [comment]
everything from the building documentation + what you suggest is installed, still errors out. :(

**Comment by wenusch** [comment]
For running the deamon you could try using docker: https://github.com/emarkproject/eMark/pull/31 
If your interested, I'll create a new repository for running the Qt wallet within a docker porting the gui to your environment. Just let me know

**Comment by dem-ionz** [comment]
Builds great, fresh install of 16.04 LTS. Sure it works great on 17.04 as tested above. Issue was on my end, closing. Thanks for fixing this issue. Closing issue. Thanks. ;) Broatcast is the man. ;) <3
