### ISSUE TITLE
Wallet OUT OF SYNC on MAC

### ISSUE THREAD

**Issue by leonardobarrientosc** [emarkproject/eMark#37]
All the time says: Out of Sync

**Comment by emarkproject** [comment]
If you use V1.4.1 there is a known problem.
Please open the wallet, go to Help -> Debug Window and open tab "Console"
Now type:
`addnode 185.194.142.165 add`
more nodes you can found here:
[](https://status.deutsche-emark.de/)

**Comment by leonardobarrientosc** [comment]
Yes, but ... the link in "Download Wallet" for Mac is https://deutsche-emark.de/files/eMark-Qt-1.4.1-mac.zip   1.4.1   I will do the add node.

**Comment by leonardobarrientosc** [comment]
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused
connect() to 85.214.246.63:5556 failed after select(): Connection refused

**Comment by emarkproject** [comment]
yes, this right. This is the hardcodet IP from our old server. This server is no longer available.
