### ISSUE TITLE
[Mining] DEM rejected blocks

### ISSUE THREAD

**Issue by goodthebest** [emarkproject/eMark#44]
Hey eMark Devs @Rumhocker @Broatcast 
I'm getting DEM blocks rejected, what RPC encoding is needed for a successful block, POS or POW?

**Comment by drphipps** [comment]
Are you using Yiimp Pool software by chance?  Getting the same issue with DEM and LINDA, both POS/POW Coins.

Possible solution here?
https://github.com/216k155/Yiimp-PHI1612-Implemented

**Comment by drphipps** [comment]
if(strcmp(coind->symbol, "DEM") == 0){if(coind->txmessage){strcat(templ->coinb2, "00");}} //fixes eMark.
       
coinbase.cpp in yiimp/stratum/

go to bottom of the file and you'll see the commented out version of the 2nd and 3rd lines, replace those with these 3.

once done, save, then sudo make, and sudo mv stratum /var/stratum/   it will overwrite the existing file, but not kill already running ones. then just restart sha, and poof, dem is back baby!*

Compliments of the Geniuses hanging out at Coinstop.me @LT1428 deserves the credit
