### ISSUE TITLE
{MINING} I run a yiimp based pool.

### ISSUE THREAD

**Issue by Controlhosting** [emarkproject/eMark#45]
i run a yiimp based pool and every block is being rejected at stratum.

**Comment by drphipps** [comment]
if(strcmp(coind->symbol, "DEM") == 0){if(coind->txmessage){strcat(templ->coinb2, "00");}} //fixes eMark.
       
coinbase.cpp in yiimp/stratum/

go to bottom of the file and you'll see the commented out version of the 2nd and 3rd lines, replace those with these 3.

once done, save, then sudo make, and sudo mv stratum /var/stratum/   it will overwrite the existing file, but not kill already running ones. then just restart sha, and poof, dem is back baby!*

Compliments of the Geniuses hanging out at Coinstop.me @LT1428 deserves the credit

**Comment by Controlhosting** [comment]
{SOLVED} Thanks @JoeH
