### ISSUE TITLE
RPC sendtoaddress method does not accept the last parameter

### ISSUE THREAD

**Issue by validierungcc** [emarkproject/eMark#81]
"sendtoaddress" has the following definition according to the help:
`sendtoaddress <eMarkAddress> <amount> [comment] [comment-to] [tx-comment]`

Actual behavior:
However, it will only accept 4 parameters, making it impossible to set a tx-comment.

Expected behavior:
Accepting 5 parameters and being able to set a tx-comment.

**Comment by MrLawrence** [comment]
merged fix
